
jwt:
  secret: U2FtcGxlU2VjcmV0S2V5U3RyaW5nRm9ySldUU2lnbmluZw==
  expiration: 3600000

spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/event_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer